package mx.unam.citas_medicas.modelo;
// Generated 11/06/2015 07:06:02 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private Integer idCit;
     private Doctor doctor;
     private Estatus estatus;
     private Paciente paciente;
     private Date fecha;
     private Date hora;

    public Cita() {
    }

    public Cita(Doctor doctor, Estatus estatus, Paciente paciente, Date fecha, Date hora) {
       this.doctor = doctor;
       this.estatus = estatus;
       this.paciente = paciente;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getIdCit() {
        return this.idCit;
    }
    
    public void setIdCit(Integer idCit) {
        this.idCit = idCit;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Estatus getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Estatus estatus) {
        this.estatus = estatus;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idCit != null ? idCit.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Cita)) {
            return false;
        }
        Cita other = (Cita) object;
        if ((this.idCit == null && other.idCit != null) || (this.idCit != null && !this.idCit.equals(other.idCit))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "modelo.Cita [ idCit=" + idCit + " ]";
    }


}


