package mx.unam.citas_medicas.modelo;
// Generated 11/06/2015 07:06:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Consultorio generated by hbm2java
 */
public class Consultorio  implements java.io.Serializable {


    private int consultorio;
    private Set doctors = new HashSet(0);

    public Consultorio() {
        
    }

	
    public Consultorio(int consultorio) {
        this.consultorio = consultorio;
    }
    public Consultorio(int consultorio, Set doctors) {
       this.consultorio = consultorio;
       this.doctors = doctors;
    }
   
    public int getConsultorio() {
        return this.consultorio;
    }
    
    public void setConsultorio(int consultorio) {
        this.consultorio = consultorio;
    }
    public Set getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set doctors) {
        this.doctors = doctors;
    }

    @Override
    public String toString() {
        return String.valueOf(consultorio);
    }
    



}


