package mx.unam.citas_medicas.modelo;
// Generated 11/06/2015 07:06:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private String rfc;
     private Consultorio consultorio;
     private Especialidad especialidad;
     private Turno turno;
     private Usuario usuario;
     private String nombre;
     private Set citas = new HashSet(0);

    public Doctor() {
    }

	
    public Doctor(String rfc) {
        this.rfc = rfc;
    }
    public Doctor(String rfc, Consultorio consultorio, Especialidad especialidad, Turno turno, Usuario usuario, String nombre, Set citas) {
       this.rfc = rfc;
       this.consultorio = consultorio;
       this.especialidad = especialidad;
       this.turno = turno;
       this.usuario = usuario;
       this.nombre = nombre;
       this.citas = citas;
    }
   
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Consultorio getConsultorio() {
        return this.consultorio;
    }
    
    public void setConsultorio(Consultorio consultorio) {
        this.consultorio = consultorio;
    }
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (rfc != null ? rfc.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Doctor)) {
            return false;
        }
        Doctor other = (Doctor) object;
        if ((this.rfc == null && other.rfc != null) || (this.rfc != null && !this.rfc.equals(other.rfc))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Doctor[ rfc=" + rfc + " ]";
    }
    


}


