package mx.unam.citas_medicas.modelo;
// Generated 11/06/2015 07:06:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Especialidad generated by hbm2java
 */
public class Especialidad  implements java.io.Serializable {


     private String especialidad;
     private Set doctors = new HashSet(0);

    public Especialidad() {
    }

	
    public Especialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public Especialidad(String especialidad, Set doctors) {
       this.especialidad = especialidad;
       this.doctors = doctors;
    }
   
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public Set getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set doctors) {
        this.doctors = doctors;
    }
    
     @Override
    public int hashCode() {
        int hash = 0;
        hash += (especialidad != null ? especialidad.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Especialidad)) {
            return false;
        }
        Especialidad other = (Especialidad) object;
        if ((this.especialidad == null && other.especialidad != null) || (this.especialidad != null && !this.especialidad.equals(other.especialidad))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "mx.unam.citas_medicas.modelo.Especialidad[ especialidad=" + especialidad + " ]";
    }



}


