package mx.unam.citas_medicas.modelo;
// Generated 11/06/2015 07:06:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estatus generated by hbm2java
 */
public class Estatus  implements java.io.Serializable {


     private int idEst;
     private String descripcion;
     private Set citas = new HashSet(0);

    public Estatus() {
    }

	
    public Estatus(int idEst) {
        this.idEst = idEst;
    }
    public Estatus(int idEst, String descripcion, Set citas) {
       this.idEst = idEst;
       this.descripcion = descripcion;
       this.citas = citas;
    }
   
    public int getIdEst() {
        return this.idEst;
    }
    
    public void setIdEst(int idEst) {
        this.idEst = idEst;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }

    @Override
    public String toString() {
        return "mx.unam.citas_medicas.modelo.Estatus[ idEst=" + idEst + " ]";
    }


}


