package mx.unam.citas_medicas.modelo;


import java.util.HashSet;
import java.util.Set;


/**
 * Usuario generated by hbm2java
 */

public class Usuario  implements java.io.Serializable {


     private Integer idUs;

     private String nombre;

     private String password;
     private Set doctors = new HashSet(0);
     private Set administradors = new HashSet(0);
     private Set pacientes = new HashSet(0);

    public Usuario() {
    }
    
    public Usuario(String nombre) {
        this.nombre=nombre;
    }
    public Usuario(String nombre, String password, Set doctors, Set administradors, Set pacientes) {
       this.nombre = nombre;
       this.password = password;
       this.doctors = doctors;
       this.administradors = administradors;
       this.pacientes = pacientes;
    }
   
    public Integer getIdUs() {
        return this.idUs;
    }
    
    public void setIdUs(Integer idUs) {
        this.idUs = idUs;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set doctors) {
        this.doctors = doctors;
    }
    public Set getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idUs != null ? idUs.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Usuario)) {
            return false;
        }
        Usuario other = (Usuario) object;
        if ((this.idUs == null && other.idUs != null) || (this.idUs != null && !this.idUs.equals(other.idUs))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "mx.unam.citas_medicas.modelo.Usuario[ idUs=" + idUs + " nombre: "+nombre+"]";
    }


}


